apiVersion: e2e.mayadata.io/v1alpha1
kind: MasterPlan
metadata:
  name: litmus-e2e-master-testplan
spec:
  tests:
  # -------------------------------------------------
  # Kubernetes openebs target chaos experiment BDDs
  # -------------------------------------------------
  - tcid: TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-POD-FAILURE
    name: "TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-POD-FAILURE"
    description: "Kills the cstor/jiva target/controller pod"
    labels:
      test/feature: "OpenEBS-App"
      test/tags: "target, pod, controller"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/openebs-pipeline/openebs-target-pod-failure"
      test/status: "Done"

  - tcid: TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-CONTAINER-FAILURE
    name: "TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-CONTAINER-FAILURE"
    description: "Kills the cstor target/Jiva controller container"
    labels:
      test/feature: "OpenEBS-App"
      test/tags: "target, container, controller"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/openebs-pipeline/openebs-target-container-failure"
      test/status: "Done"

  - tcid: TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-NETWORK-DELAY
    name: "TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-NETWORK-DELAY"
    description: "Injects network delay in storage target and verifies the application availability"
    labels:
      test/feature: "OpenEBS-App"
      test/tags: "target, network, controller"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/openebs-pipeline/openebs-target-network-delay"
      test/status: "Done"

  - tcid: TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-NETWORK-LOSS
    name: "TCID-VMWx-OPENEBS-APP-OPENEBS-TARGET-NETWORK-LOSS"
    description: "Inject network loss on storage target/controller"
    labels:
      test/feature: "Generic-App"
      test/tags: "network, storage,pod"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/openebs-pipeline/openebs-target-network-loss"
      test/status: "Done"

  # -------------------------------------------------
  # Kubernetes openebs Pool chaos experiment BDDs
  # -------------------------------------------------

  - tcid: TCID-VMWx-OPENEBS-APP-OPENEBS-POOL-CONTAINER-FAILURE
    name: "TCID-VMWx-OPENEBS-APP-OPENEBS-POOL-CONTAINER-FAILURE"
    description: "Kill the pool container and check if it gets scheduled again"
    labels:
      test/feature: "OpenEBS-App"
      test/tags: "Pool, container"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/openebs-pipeline/openebs-pool-container-failure"
      test/status: "Done"

  - tcid: TCID-VMWx-OPENEBS-APP-OPENEBS-POOL-POD-FAILURE
    name: "TCID-VMWx-OPENEBS-APP-OPENEBS-POOL-POD-FAILURE"
    description: "Kill the pool pod and check if gets scheduled again"
    labels:
      test/feature: "OpenEBS-App"
      test/tags: "Pool, pod"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/openebs-pipeline/openebs-pool-pod-failure"
      test/status: "Done"

  # -------------------------------------------------
  # Kubernetes openebs control plane experiment BDDs
  # -------------------------------------------------

  - tcid: TCID-VMWx-OPENEBS-APP-OPENEBS-CONTROL-PLANE-CHAOS
    name: "TCID-VMWx-OPENEBS-APP-OPENEBS-CONTROL-PLANE-CHAOS"
    description: "Kill the OpenEBS control plane pods and check if they are rescheduled and healthy"
    labels:
      test/feature: "OpenEBS-App"
      test/tags: "control-plane, pod"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/openebs-pipeline/openebs-control-plane-chaos"
      test/status: "Done"

