apiVersion: e2e.mayadata.io/v1alpha1
kind: MasterPlan
metadata:
  name: litmus-e2e-master-testplan
spec:
  tests:
  # ----------------------------------------------------------
  # Kubernetes generic application level chaos experiment BDDs
  # ----------------------------------------------------------
  - tcid: TCID-VMWx-GENERIC-APP-POD-DELETE
    name: "TCID-VMWx-GENERIC-APP-POD-DELETE"
    description: "Fail the application pod"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, kill"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/pod-delete"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-APP-CONTAINER-KILL
    name: "TCID-VMWx-GENERIC-APP-CONTAINER-KILL"
    description: "Kill one container in the application pod"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, container"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/container-kill"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-APP-POD-CPU-HOG
    name: "TCID-VMWx-GENERIC-APP-POD-CPU-HOG"
    description: "Consume CPU resources on the application container"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, cpu,container"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/pod-cpu-hog"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-APP-POD-MEMORY-HOG
    name: "TCID-VMWx-GENERIC-APP-POD-MEMORY-HOG"
    description: "Consume memory resources on the application container"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, memory"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/pod-memory-hog"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-APP-POD-NETWORK-CORRUPTION
    name: "TCID-VMWx-GENERIC-APP-POD-NETWORK-CORRUPTION"
    description: "Inject Network Packet Corruption Into Application Pod"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, network, corruption"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/pod-network-corruption"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-APP-POD-NETWORK-LATENCY
    name: "TCID-VMWx-GENERIC-APP-POD-NETWORK-LATENCY"
    description: "Inject Network Latency Into Application Pod"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, network, latency"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/pod-network-latency"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-APP-POD-NETWORK-LOSS
    name: "TCID-VMWx-GENERIC-APP-POD-NETWORK-LOSS"
    description: "Inject Packet Loss Into Application Pod"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, network, loss"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/pod-network-loss"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-APP-POD-NETWORK-DUPLICATION
    name: "TCID-VMWx-GENERIC-APP-POD-NETWORK-DUPLICATION"
    description: "Inject Network Duplication Into Application Pod"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, network, duplication"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/pod-network-duplication"
      test/status: "Not Done"

  - tcid: TCID-VMWx-GENERIC-APP-DISK-FILL
    name: "TCID-VMWx-GENERIC-APP-DISK-FILL"
    description: "Fill up Ephemeral Storage of a Pod"
    labels:
      test/feature: "Generic-App"
      test/tags: "pod, ephemeral, disk"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/disk-fill"
      test/status: "Done"      

  # ----------------------------------------------------------
  # Kubernetes Infra level chaos experiment BDDs
  # ----------------------------------------------------------

  - tcid: TCID-VMWx-GENERIC-INFRA-NODE-CPU-HOG
    name: "TCID-VMWx-GENERIC-APP-NODE-CPU-HOG"
    description: "Exhaust CPU resources on the Kubernetes Node"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "node, cpu, spike"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/disk-fill"
      test/status: "Done" 

  - tcid: TCID-VMWx-GENERIC-INFRA-NODE-MEMORY-HOG
    name: "TCID-VMWx-GENERIC-INFRA-NODE-MEMORY-HOG"
    description: "Exhaust Memory resources on the Kubernetes Node"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "node, memory, hog"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/node-memory-hog"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-INFRA-NODE-DRAIN
    name: "TCID-VMWx-GENERIC-INFRA-NODE-DRAIN"
    description: "Drain the node where application pod is scheduled"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "node, drain"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/node-drain"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-INFRA-KUBELET-SERVICE-KILL
    name: "TCID-VMWx-GENERIC-INFRA-KUBELET-SERVICE-KILL"
    description: "Kills the kubelet service on the application node to check the resiliency"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "kubelet, service, kill"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/kubelet-service-kill"
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-INFRA-DISK-LOSS
    name: "TCID-VMWx-GENERIC-INFRA-DISK-LOSS"
    description: "External disk loss from the node"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "disk, loss"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/disk-loss"
      test/status: "Not Done"

  - tcid: TCID-VMWx-GENERIC-INFRA-NODE-TAINT
    name: "TCID-VMWx-GENERIC-INFRA-NODE-TAINT"
    description: "Taint the application node"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "node, taint"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/master/generic-pipeline/node-taint"
      test/status: "Done"

  # ----------------------------------------------------------
  # LitmusChaos Operator BDDs
  # ----------------------------------------------------------

  - tcid: TCID-VMWx-GENERIC-CONTROL-OPERATOR-RECONCILE-RESILIENCY
    name: "TCID-VMWx-GENERIC-CONTROL-OPERATOR-RECONCILE-RESILIENCY"
    description: "Tests the Reconcile Resiliency of Litmus Operator"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "operator, litmus, resiliency"
      git/location: ""
      test/status: "Done"

  - tcid: TCID-VMWx-GENERIC-CONTROL-ADMIN-MODE
    name: "TCID-VMWx-GENERIC-CONTROL-ADMIN-MODE"
    description: "Test the admin mode functionality"
    labels:
      test/feature: "Generic-Infra"
      test/tags: "admin-mode, operator, litmus"
      git/location: ""
      test/status: "Done"
