apiVersion: e2e.mayadata.io/v1alpha1
kind: MasterPlan
metadata:
  name: litmus-e2e-master-testplan
spec:
  tests:
  # ----------------------------------------------------------
  # Cypress UI Tests for Litmus-portal for Self Cluster
  # ----------------------------------------------------------
  - tcid: TCID-VMWx-Portal-GUI-Auth
    name: "TCID-VMWx-Portal-GUI-Auth"
    description: "UI Tests for Login and Welcome Modal Functionalities"
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "Basic,UI"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/litmus-portal/CypressE2E/cypress/integration/Basic_Setup"
      test/status: "Done"

  - tcid: TCID-VMWx-Portal-GUI-AccountSettings
    name: "TCID-VMWx-Portal-GUI-AccountSettings"
    description: "UI Tests for Settings and Teaming Tab"
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "Account Setting,Teaming,UI"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/litmus-portal/CypressE2E/cypress/integration/Parallel_Tests/Account_Settings"
      test/status: "Done"
  
  - tcid: TCID-VMWx-Portal-GUI-BrowseWorkflows
    name: "TCID-VMWx-Portal-GUI-BrowseWorkflows"
    description: "UI Tests for Workflow tables Browsing"
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "Worklows and schedules tables,UI"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/litmus-portal/CypressE2E/cypress/integration/Parallel_Tests/BrowseWorkflow"
      test/status: "Done"

  - tcid: TCID-VMWx-Portal-GUI-CommunityData
    name: "TCID-VMWx-Portal-GUI-CommunityData"
    description: "UI Tests for Community Tab ( Community and Geo Analytics)"
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "Community data,UI"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/litmus-portal/CypressE2E/cypress/integration/Parallel_Tests/Community"
      test/status: "Done"
  
  - tcid: TCID-VMWx-portal-GUI-ScheduleWorkflow
    name: "TCID-VMWx-portal-GUI-ScheduleWorkflow"
    description: "UI Tests for Workflow Scheduling Scenarios (Different Scenarios for scheduling workflow)."
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "Workflow Scheduling,UI"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/litmus-portal/CypressE2E/cypress/integration/Parallel_Tests/Create_Workflow"
      test/status: "Done"

  - tcid: TCID-VMWx-Portal-GUI-Routes
    name: "TCID-VMWx-Portal-GUI-Routes"
    description: "UI Tests for routes checks (Authorized and Unautorized)"
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "Routes Checks,UI"
      git/location: "https://github.com/litmuschaos/litmus-e2e/tree/litmus-portal/CypressE2E/cypress/integration/Parallel_Tests/Routes"
      test/status: "Done"

  - tcid: TCID-VMWx-Portal-GUI-MyHub
    name: "TCID-VMWx-Portal-GUI-MyHub"
    description: "UI Tests for MyHub"
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "MyHub Checks,UI"
      git/location: ""
      test/status: "Not Done"

  - tcid: TCID-VMWx-Portal-GUI-Analytics
    name: "TCID-VMWx-Portal-GUI-Analytics"
    description: "UI Tests for Workflow Analytics"
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "Analytics Checks,UI"
      git/location: ""
      test/status: "Not Done"
  
  # ----------------------------------------------------------
  #   Cypress UI Tests for External Cluster or Agent
  # ----------------------------------------------------------
  - tcid: TCID-VMWx-Portal-Cluster-External-Cluster-Register
    name: "TCID-VMWx-Portal-Cluster-External-Cluster-Register"
    description: "Tests for External Agent or Cluster Registration."
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "External-Cluster,Cluster-Registration"
      git/location: ""
      test/status: "Not Done"
  
  - tcid: TCID-VMWx-Portal-Cluster-External-Cluster-WorkflowScheduling
    name: "TCID-VMWx-Portal-Cluster-External-Cluster-WorkflowScheduling"
    description: "Tests Scheduling Workflows on External Agent."
    labels:
      test/feature: "Litmus-Portal"
      test/tags: "External-Cluster, Workflow-Scheduling"
      git/location: ""
      test/status: "Not Done"