#!/bin/bash
set -e

## set pipeline veriables
echo "set pipeline veriables"
export CI_JOB_ID=${CI_JOB_ID}
export CI_PIPELINE_ID=${CI_PIPELINE_ID}
export GITHUB_TOKEN=${GITHUB_TOKEN}
export CGO_ENABLED=0

## set image variables
echo "set image variables"
export ANSIBLE_EXPERIMENT_IMAGE=${ANSIBLE_EXPERIMENT_IMAGE}
export GO_EXPERIMENT_IMAGE=${GO_EXPERIMENT_IMAGE}
export OPERATOR_IMAGE=${OPERATOR_IMAGE}
export RUNNER_IMAGE=${RUNNER_IMAGE}

## set experiment variables
echo "set experiment variables"
export OPERATOR_NAME=${OPERATOR_NAME}
export CHAOS_NAMESPACE=${CHAOS_NAMESPACE}
export APP_NS=${APP_NS}
export APP_LABEL=${APP_LABEL}
export JOB_CLEANUP_POLICY=${JOB_CLEANUP_POLICY}
export ANNOTATION_CHECK=${ANNOTATION_CHECK}
export APPLICATION_NODE_NAME=${APPLICATION_NODE_NAME}
export IMAGE_PULL_POLICY=${IMAGE_PULL_POLICY}
export TOTAL_CHAOS_DURATION=${TOTAL_CHAOS_DURATION}

## set link variables
echo "set link variables"
export RBAC_PATH=${RBAC_PATH}
export EXPERIMENT_PATH=${EXPERIMENT_PATH}
export ENGINE_PATH=${ENGINE_PATH}
export ANSIBLE_RBAC_PATH=${ANSIBLE_RBAC_PATH}
export ANSIBLE_EXPERIMENT_PATH=${ANSIBLE_EXPERIMENT_PATH}
export ANSIBLE_ENGINE_PATH=${ANSIBLE_ENGINE_PATH}
export INSTALL_LITMUS=${INSTALL_LITMUS}
export ADMIN_RBAC_PATH=${ADMIN_RBAC_PATH}
