## Node level experiment test will trigger 
## only if POD_LEVEL variable is set to true

TCID-VMWx-GENERIC-INFRA-NODE-CPU-HOG:
  when: always
  stage: Infra Experiment
  tags: 
    - node-level-test
  script:
    - make node-cpu-hog
  only:
    variables:
    - $NODE_LEVEL == "true"                

TCTCID-VMWx-GENERIC-INFRA-POD-AUTOSCALER:
  when: always
  stage: Infra Experiment   
  tags:
    - node-level-test
  script:
    - make pod-autoscaler 
  only:
    variables:
    - $NODE_LEVEL == "true"                

TCID-VMWx-GENERIC-INFRA-NODE-CPU-HOG:
  when: always
  stage: Infra Experiment
  tags: 
    - node-level-test
  script:
    - make node-cpu-hog
  only:
    variables:
    - $NODE_LEVEL == "true"                

TCID-VMWx-GENERIC-INFRA-NODE-MEMORY-HOG:
  when: always
  stage: Infra Experiment
  tags:
    - node-level-test
  script:
    - make node-memory-hog
  only:
    variables:
    - $NODE_LEVEL == "true"          

TCID-VMWx-GENERIC-INFRA-NODE-DRAIN:
  when: always
  stage: Infra Experiment
  tags:
    - node-level-test
  script:
    - make node-drain
  only:
    variables:
    - $NODE_LEVEL == "true"          

TCID-VMWx-GENERIC-INFRA-KUBELET-SERVICE-KILL:
  when: always
  stage: Infra Experiment
  tags:
    - node-level-test
  script:
    - make kubelet-service-kill
  only:
    variables:
    - $NODE_LEVEL == "true"           

TCID-VMWx-GENERIC-INFRA-NODE-TAINT:
  when: always
  stage: Infra Experiment
  tags:
    - node-level-test
  script:
    - make node-taint
  only:
    variables:
    - $NODE_LEVEL == "true"          
      
TCID-VMWx-GENERIC-INFRA-NODE-IO-STRESS:
  when: always
  stage: Infra Experiment
  tags:
    - node-level-test
  script:
    - make node-io-stress
  only:
    variables:
    - $NODE_LEVEL == "true"                 

TCID-VMWx-ANSIBLE-INFRA-NODE-CPU-HOG:
  when: always
  stage: Ansible Experiment 
  tags:
    - node-level-test
  script:
    - make ansible-node-cpu-hog
  only:
    variables:
    - $NODE_LEVEL_ANSIBLE_JOB == "true"

TCID-VMWx-ANSIBLE-INFRA-NODE-MEMORY-HOG:
  when: always
  stage: Ansible Experiment 
  tags:
    - node-level-test
  script:
    - make ansible-node-memory-hog
  only:
    variables:
    - $NODE_LEVEL_ANSIBLE_JOB == "true" 

TCID-VMWx-ANSIBLE-INFRA-KUBELET-SERVICE-KILL:
  when: always
  stage: Ansible Experiment 
  tags:
    - node-level-test
  script:
    - make ansible-kubelet-service-kill
  only:
    variables:
    - $NODE_LEVEL_ANSIBLE_JOB == "true"
    
TCID-VMWx-ANSIBLE-INFRA-NODE-DRAIN:
  when: always
  stage: Ansible Experiment 
  tags:
    - node-level-test
  script:
    - make ansible-node-drain
  only:
    variables:
    - $NODE_LEVEL_ANSIBLE_JOB == "true"      

App Cleanup In Cluster-2:
  when: always
  stage: App Cleanup
  tags: 
    - node-level-test
  script:
    - make app-cleanup 
  only:
    variables:
    - $NODE_LEVEL == "true"       
