## Pod level experiment test will trigger 
## only if POD_LEVEL variable is set to true

Litmus Infra Setup In Cluster-1:
  when: always
  stage: install
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make build-litmus-cluster-1
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"      

Deploy App In Cluster-1:
  when: always
  stage: deploy
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make app-deploy-cluster-1
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

Liveness In Cluster-1:
  when: always
  stage: deploy
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make liveness-cluster-1
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

Auxiliary App In Cluster-1:
  when: always
  stage: deploy
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make auxiliary-app-cluster-1
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-DELETE:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-delete
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-CONTAINER-KILL:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make container-kill
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-CPU-HOG:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-cpu-hog
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-MEMORY-HOG:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-memory-hog
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-NETWORK-CORRUPTION:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-network-corruption
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-NETWORK-LATENCY:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-network-latency
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-NETWORK-LOSS:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-network-loss
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-NETWORK-DUPLICATION:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-network-duplication
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

TCID-VMWx-GENERIC-APP-POD-IO-STRESS:
  when: always
  stage: Generic Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make pod-io-stress
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"        


TCID-VMWx-GENERIC-APP-DISK-FILL:
  when: always
  stage: Infra Experiment
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make disk-fill
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"       

## Ansible Experiments will trigger 
## only if ANSIBLE_JOB is set to true

TCID-VMWx-ANSIBLE-APP-POD-DELETE:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-pod-delete
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"

TCID-VMWx-ANSIBLE-APP-CONTAINER-KILL:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-container-kill
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"

TCID-VMWx-ANSIBLE-APP-DISK-FILL:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-disk-fill
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"

TCID-VMWx-ANSIBLE-APP-POD-CPU-HOG:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-pod-cpu-hog
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"

TCID-VMWx-ANSIBLE-APP-POD-MEMORY-HOG:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-pod-memory-hog
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"

TCID-VMWx-ANSIBLE-APP-POD-NETWORK-CORRUPTION:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-pod-network-corruption
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"

TCID-VMWx-ANSIBLE-APP-POD-NETWORK-LATENCY:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-pod-network-latency
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"   

TCID-VMWx-ANSIBLE-APP-POD-NETWORK-LOSS:
  when: always
  stage: Ansible Experiment 
  tags:
    - litmus-build
    - pod-level-test
  script:
    - make ansible-pod-network-loss
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL_ANSIBLE_JOB == "true"    

App Cleanup In Cluster-1:
  when: always
  stage: App Cleanup
  tags: 
    - litmus-build
    - pod-level-test
  script:
    - make app-cleanup-cluster-1
  artifacts:
    when: always
    paths:
      - .kube/
  only:
    variables:
    - $POD_LEVEL == "true"
      