apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  annotationCheck: 'false'
  engineState: 'active'
  auxiliaryAppInfo: ''
  chaosServiceAccount: pod-autoscaler-sa
  monitoring: false
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-autoscaler
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            - name: REPLICA_COUNT
              value: '5'
              