name: automerge-CI
on:
  issue_comment:
    types: [created]

jobs:

  # This job will merge an equipped PR in two steps:
  # First it will add a merge label to the PR
  # Then it will merge the PR based on the checks that is only if all checks are passed
  merge:  
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/merge')
    runs-on: ubuntu-latest
    steps:
      - name: Add a merge label 
        uses: actions-ecosystem/action-add-labels@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labels: merge

      # The action will check if the required number of review approvals has been reached by verifying the default checks   
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:          
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "merge,!WIP,!DO NOT MERGE"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
          MERGE_DELETE_BRANCH: false