---
name: Component-Pipeline
on:
  workflow_dispatch:
    inputs:
      e2eTestImage:
        default: 'litmuschaos/litmus-e2e:ci'
      goExperimentImage:
        default: 'litmuschaos/go-runner:ci'
      newLibImage:
        default: 'litmuschaos/go-runner:ci'
      oldLibImage:
        default: 'litmuschaos/go-runner:latest'        
      operatorImage:
        default: 'litmuschaos/chaos-operator:ci'
      runnerImage:
        default: 'litmuschaos/chaos-runner:ci'
      chaosNamespace:
        default: 'litmus'
      imagePullPolicy:
        default: 'Always'
      experimentImagePullPolicy:
        default: 'Always'
      updateWebsite: 
        default: 'false'
        
jobs:

### Setup Litmus

  Setup_Litmus_Infra:
    container: 
      image: "${{ github.event.inputs.e2eTestImage }}"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
      env:
        OPERATOR_IMAGE: "${{ github.event.inputs.operatorImage }}"
        OPERATOR_NAME: "${{ github.event.inputs.operatorName }}"        
        RUNNER_IMAGE: "${{ github.event.inputs.runnerImage }}"
        IMAGE_PULL_POLICY: "${{ github.event.inputs.imagePullPolicy }}"
        KUBECONFIG: /root/.kube/config
        
    runs-on: self-hosted
    steps:
      - name: Litmus Infra Setup In Cluster-1
        working-directory: /go/src
        run: |
          make build-litmus
        
### Setup App
        
  Setup_App_Deployment:
    needs:  Setup_Litmus_Infra
    container: 
      image: "${{ github.event.inputs.e2eTestImage }}"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config
        
    runs-on: self-hosted
    steps:
      - name: Deploy App In Cluster-1
        working-directory: /go/src
        run: make build-litmus        

      - name: Liveness In Cluster-1
        if: ${{ always() }}
        working-directory: /go/src
        run: make build-litmus        

      - name: Auxiliary App In Cluster-1
        if: ${{ always() }}
        working-directory: /go/src
        run: make build-litmus
        
### Runing Component Tests        
        
  Component_Test:
    needs: Setup_App_Deployment
    container: 
      image: "${{ github.event.inputs.e2eTestImage }}"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
      env:
        GO_EXPERIMENT_IMAGE: "${{ github.event.inputs.goExperimentImage }}"        
        NEW_LIB_IMAGE: "${{ github.event.inputs.newLibImage }}" 
        OLD_LIB_IMAGE: "${{ github.event.inputs.oldLibImage }}"                
        EXPERIMENT_IMAGE_PULL_POLICY: "${{ github.event.inputs.experimentImagePullPolicy }}"
        CHAOS_NAMESPACE: "${{ github.event.inputs.chaosNamespace }}"
        UPDATE_WEBSITE: "${{ github.event.inputs.updateWebsite }}"
        KUBECONFIG: /root/.kube/config
        
    runs-on: self-hosted
    steps:
      - name: TCID-EC2-GENERIC-OPERATOR-RECONCILE-RESILIENCY
        working-directory: /go/src      
        run: make operator-reconcile-resiliency-check

      - name: TCID-EC2-GENERIC-OPERATOR-ADMIN-MODE
        if: ${{ always() }}
        working-directory: /go/src        
        run: make admin-mode-check

      - name: TCID-EC2-GENERIC-ENGINE-APP-INFO
        if: ${{ always() }}
        working-directory: /go/src        
        run: make appinfo

      - name: TCID-EC2-GENERIC-ENGINE-ANNOTATION-CHECK
        if: ${{ always() }}
        working-directory: /go/src        
        run: make annotation-check
        
      - name: TCID-EC2-GENERIC-ENGINE-ENGINE-STATE
        if: ${{ always() }}
        working-directory: /go/src        
        run: make engine-state
        
      - name: TCID-EC2-GENERIC-ENGINE-JOB-CLEANUP-POLICY
        if: ${{ always() }}
        working-directory: /go/src        
        run: make job-cleanup-policy     
        
      - name: TCID-EC2-GENERIC-ENGINE-SERVICE-ACCOUNT
        if: ${{ always() }}
        working-directory: /go/src        
        run: make service-account 
        
      - name: TCID-EC2-GENERIC-EXPERIMENT-EXPERIMENT-IMAGE-NAME
        if: ${{ always() }}
        working-directory: /go/src        
        run: make experiment-image
        
      - name: TCID-EC2-GENERIC-EXPERIMENT-TARGET-POD
        if: ${{ always() }}
        working-directory: /go/src        
        run: make target-pod          

### App Cleanup

  App_Cleanup:
    needs: Component_Test
    if: always()
    container: 
      image: "${{ github.event.inputs.e2eTestImage }}"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config
        
    runs-on: self-hosted
    steps:
      - name: Application Cleanup
        working-directory: /go/src      
        run: make app-cleanup

### Litmus Cleanup 

  Litmus_Cleanup:
    needs: App_Cleanup
    if: always()
    container: 
      image: "${{ github.event.inputs.e2eTestImage }}"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config
        COMPONENT_TEST: "true"   

    runs-on: self-hosted
    steps:
      - name: Litmus Cleanup
        working-directory: /go/src      
        run: make litmus-cleanup
