---
name: Nightly-Node-Level-Pipeline
on:
  schedule:
    - cron: "30 20 * * *" # Daily 02:30 AM in midnight

defaults:
  run:
    working-directory: /go/src

jobs:
  ### Setup Litmus
  Setup_Litmus_Infra:
    container:
      image: "litmuschaos/litmus-e2e:ci"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /home/ubuntu/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config

    runs-on: [self-hosted, node-level]

    steps:
      - name: Litmus Infra Setup In Cluster-3
        run: |
          make build-litmus

  ### Setup App
  Setup_App_Deployment:
    needs: Setup_Litmus_Infra
    container:
      image: "litmuschaos/litmus-e2e:ci"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /home/ubuntu/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config

    runs-on: [self-hosted, node-level]
    steps:
      - name: Deploy App In Cluster-3
        run: make app-deploy

    ## TODO: Make use of app liveness check and aux app
    # - name: Liveness In Cluster-3
    #   if: always()
    #   run: make liveness

    # - name: Auxiliary App In Cluster-3
    #   if: always()
    #   run: make auxiliary-app

  ### Runing Pod Level Tests

  Node_Level_Test:
    needs: Setup_App_Deployment
    if: always()
    container:
      image: "litmuschaos/litmus-e2e:ci"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /home/ubuntu/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config

    runs-on: [self-hosted, node-level]
    steps:
      - name: TCID-EC2-GENERIC-INFRA-POD-AUTOSCALER
        run: make pod-autoscaler

      - name: TCID-EC2-GENERIC-INFRA-NODE-CPU-HOG
        if: always()
        run: make node-cpu-hog

      - name: TCID-EC2-GENERIC-INFRA-NODE-MEMORY-HOG
        if: always()
        run: make node-memory-hog

      - name: TCID-EC2-GENERIC-INFRA-NODE-DRAIN
        if: always()
        run: make node-drain

      - name: TCID-EC2-GENERIC-INFRA-KUBELET-SERVICE-KILL
        if: always()
        run: make kubelet-service-kill

      - name: TCID-EC2-GENERIC-INFRA-NODE-TAINT
        if: always()
        run: make node-taint

      - name: TCID-EC2-GENERIC-INFRA-NODE-IO-STRESS
        if: always()
        run: make node-io-stress

      - name: TCID-EC2-GENERIC-INFRA-NODE-SELECTOR
        if: always()
        run: make node-selector

      - name: "[Debug]: check chaos resources"
        if: ${{ failure() }}
        continue-on-error: true
        run: |
          bash <(curl -s https://raw.githubusercontent.com/litmuschaos/litmus-e2e/master/build/debug.sh)
          
      - name: "[Debug]: check operator logs"
        if: ${{ failure() }}
        continue-on-error: true
        run: |      
          operator_name=$(kubectl get pods -n litmus -l app.kubernetes.io/component=operator --no-headers | awk '{print$1}')
          kubectl logs $operator_name -n litmus > logs.txt
          cat logs.txt

  ### Runing Experiment Tunables
  Engine_Test:
    needs: Node_Level_Test
    if: always()
    container:
      image: "litmuschaos/litmus-e2e:ci"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /home/ubuntu/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config

    runs-on: [self-hosted, node-level]
    steps:
      - name: TCID-EC2-GENERIC-INFRA-WITH-APP-INFO
        run: make with-app-info

      - name: "[Debug]: check chaos resources"
        if: ${{ failure() }}
        continue-on-error: true
        run: |
          bash <(curl -s https://raw.githubusercontent.com/litmuschaos/litmus-e2e/master/build/debug.sh)
          
      - name: "[Debug]: check operator logs"
        if: ${{ failure() }}
        continue-on-error: true
        run: |      
          operator_name=$(kubectl get pods -n litmus -l app.kubernetes.io/component=operator --no-headers | awk '{print$1}')
          kubectl logs $operator_name -n litmus > logs.txt
          cat logs.txt

  ### App Cleanup
  App_Cleanup:
    needs: Engine_Test
    if: always()
    container:
      image: "litmuschaos/litmus-e2e:ci"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /home/ubuntu/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config

    runs-on: [self-hosted, node-level]
    steps:
      - name: Application Cleanup
        run: make app-cleanup

  ### Litmus Cleanup

  Litmus_Cleanup:
    needs: App_Cleanup
    if: always()
    container:
      image: "litmuschaos/litmus-e2e:ci"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /home/ubuntu/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes
      env:
        KUBECONFIG: /root/.kube/config
        NODE_LEVEL: "true"

    runs-on: [self-hosted, node-level]
    steps:
      - name: Litmus Cleanup
        run: make litmus-cleanup
